# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stream_ingest.ingestion_pb2 as ingestion__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingestion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrokerStub(object):
    """The Broker service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullMessage = channel.unary_stream(
                '/ingestion.Broker/PullMessage',
                request_serializer=ingestion__pb2.PullRequest.SerializeToString,
                response_deserializer=ingestion__pb2.PullResponse.FromString,
                _registered_method=True)
        self.PushMessage = channel.unary_unary(
                '/ingestion.Broker/PushMessage',
                request_serializer=ingestion__pb2.PushRequest.SerializeToString,
                response_deserializer=ingestion__pb2.PushResponse.FromString,
                _registered_method=True)
        self.AddTopic = channel.unary_unary(
                '/ingestion.Broker/AddTopic',
                request_serializer=ingestion__pb2.AddTopicRequest.SerializeToString,
                response_deserializer=ingestion__pb2.AddTopicResponse.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/ingestion.Broker/ListTopics',
                request_serializer=ingestion__pb2.ListTopicsRequest.SerializeToString,
                response_deserializer=ingestion__pb2.ListTopicsResponse.FromString,
                _registered_method=True)


class BrokerServicer(object):
    """The Broker service definition.
    """

    def PullMessage(self, request, context):
        """Pulls a message from the broker. Used by Consumer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMessage(self, request, context):
        """Pushes a new message to the broker. Used by Producer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTopic(self, request, context):
        """Adds topic to the broker. Used by Admin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.PullMessage,
                    request_deserializer=ingestion__pb2.PullRequest.FromString,
                    response_serializer=ingestion__pb2.PullResponse.SerializeToString,
            ),
            'PushMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMessage,
                    request_deserializer=ingestion__pb2.PushRequest.FromString,
                    response_serializer=ingestion__pb2.PushResponse.SerializeToString,
            ),
            'AddTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTopic,
                    request_deserializer=ingestion__pb2.AddTopicRequest.FromString,
                    response_serializer=ingestion__pb2.AddTopicResponse.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=ingestion__pb2.ListTopicsRequest.FromString,
                    response_serializer=ingestion__pb2.ListTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.Broker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.Broker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Broker(object):
    """The Broker service definition.
    """

    @staticmethod
    def PullMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ingestion.Broker/PullMessage',
            ingestion__pb2.PullRequest.SerializeToString,
            ingestion__pb2.PullResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.Broker/PushMessage',
            ingestion__pb2.PushRequest.SerializeToString,
            ingestion__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.Broker/AddTopic',
            ingestion__pb2.AddTopicRequest.SerializeToString,
            ingestion__pb2.AddTopicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.Broker/ListTopics',
            ingestion__pb2.ListTopicsRequest.SerializeToString,
            ingestion__pb2.ListTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
